{ config, lib, pkgs, ... }:

# Xournal++ appearance — the Notion colour palette and the one-time seed that
# makes the app stop looking like 2008.
#
# WHY THIS IS NOT IN modules/apps.nix. That module installs Xournal++ and
# patches its .desktop entry, which is the same treatment every app there gets.
# This is the opposite kind of thing: per-app taste, expressed in a config
# format only this one app reads. Keeping it separate means apps.nix stays a
# list of apps rather than growing a special case per program.
#
# WHY THERE IS NOTHING HERE ABOUT GTK THEMES. Xournal++ is GTK3, and Yaru-dark
# already reaches it — traced on the running app, which opens
# /usr/share/themes/Yaru-dark/gtk-3.0/gtk.css, because the GNOME session's
# XDG_DATA_DIRS carries /usr/share and the nixpkgs wrapper only prepends to it.
# So the window chrome is already correct and already consistent with every
# other window. Forcing adw-gtk3 or any other theme onto this one app would
# make it the odd one out, which is why that is deliberately not done.
#
# What IS wrong is everything Xournal++ draws itself, none of which GTK can
# touch: the icon set, the canvas surround, the colour palette and the tool
# defaults. Those live in ~/.config/xournalpp/settings.xml and are seeded by
# modules/xournalpp-appearance.py — read its header for the seed-not-pin
# contract and why a home-manager symlink cannot be used for that file.

let
  cfg = config.modules.apps;

  # Gated on the apps bundle rather than an option of its own: this configures
  # an app that bundle installs, so it has nothing to do on a machine where the
  # app is absent. `skip` is honoured for the same reason — a machine using its
  # own Xournal++ from apt should keep that install's settings.
  enabled = cfg.enable && !(lib.elem "xournalpp" cfg.skip);

  paletteRelPath = "xournalpp/palettes/notion.gpl";
  palettePath = "${config.xdg.configHome}/${paletteRelPath}";

  # Notion's colours, as a GIMP palette — the format Xournal++ reads, and the
  # only user-extensible part of its colour picker.
  #
  # The first ten are Notion's own text colours, light mode, which is what
  # anyone means by "the Notion palette". They are muted and slightly warm,
  # where Xournal++ ships fully saturated primaries (its default pen is
  # #00FF00), so this is most of the visible difference on the page.
  #
  # The last six are NOT Notion's highlight backgrounds, and that is deliberate.
  # Notion paints those opaque behind black text, so they are near-white
  # (#FBF3DB and the like); Xournal++ draws the highlighter translucent over
  # paper, where near-white is invisible. These are the same six hues lifted 45%
  # toward white instead, which keeps the family and still reads as a highlight.
  # Generated by the snippet in the repo history; edit the numbers here.
  paletteText = ''
    GIMP Palette
    Name: Notion
    #
    # Notion's text colours as ink, plus lifted versions of six of them as
    # highlighter colours. Installed by modules/xournalpp.nix in dome.
    #
    55  53  47  Notion Default
    120 119 116 Notion Gray
    159 107 83  Notion Brown
    217 115 13  Notion Orange
    203 145 47  Notion Yellow
    68  131 97  Notion Green
    51  126 169 Notion Blue
    144 101 176 Notion Purple
    193 76  138 Notion Pink
    212 76  71  Notion Red
    226 194 141 Highlight Yellow
    152 187 168 Highlight Green
    143 184 208 Highlight Blue
    221 157 191 Highlight Pink
    234 178 122 Highlight Orange
    194 170 212 Highlight Purple
  '';
in
{
  config = lib.mkIf enabled {
    # A symlink into the store is fine HERE, unlike settings.xml: Xournal++ only
    # ever reads palette files. It scans this directory for *.gpl and lists what
    # it finds beside the built-in palettes in Preferences.
    xdg.configFile.${paletteRelPath}.text = paletteText;

    home.activation.xournalppAppearance = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
      _xpp_conf="${config.xdg.configHome}/xournalpp"
      _xpp_marker="$_xpp_conf/.dome-appearance"

      if [ -e "$_xpp_marker" ]; then
        :   # already seeded once; the settings are yours from here on
      elif ${pkgs.procps}/bin/pgrep -x xournalpp >/dev/null 2>&1; then
        # It rewrites settings.xml in full when it exits, so seeding underneath
        # a running instance would be undone the moment the window closes. No
        # marker is written, so the next switch tries again.
        echo "[xournalpp] running — appearance left alone (quit it, then re-run make home)"
      else
        run ${pkgs.python3}/bin/python3 ${./xournalpp-appearance.py} \
          "$_xpp_conf/settings.xml" "${palettePath}" && run touch "$_xpp_marker"
      fi
    '';
  };
}
