#!/usr/bin/env bash
# setup.sh — interactive machine setup for dome.
#
#   ./setup.sh                       guided TUI (whiptail; plain prompts as fallback)
#   ./setup.sh --defaults <host>     non-interactive: write user-config.nix from the
#                                    host's seed defaults (used by scripts/CI)
#
# What it does: detects the machine (distro, hardware model, WSL/Codespaces),
# suggests a host profile, lets you toggle the language/tool modules, writes
# user-config.nix, and offers to run ./install.sh.
#
# Precedence for the module checklist seeds:
#   existing user-config.nix choices  >  hosts/<host>/setup-defaults.env  >  off
set -euo pipefail
cd "$(dirname "$0")"

MODULES=(python node java ai cloud)
# Toggle state; reassigned dynamically via `declare "m_<name>=..."`.
m_python=false m_node=false m_java=false m_ai=false m_cloud=false

# ── detection ────────────────────────────────────────────────────────────────
DISTRO=unknown
[ -r /etc/os-release ] && DISTRO="$(. /etc/os-release && echo "${PRETTY_NAME:-unknown}")"
VENDOR="$(cat /sys/class/dmi/id/sys_vendor 2>/dev/null || echo unknown)"
MODEL="$(cat /sys/class/dmi/id/product_name 2>/dev/null || echo unknown)"
KERNEL="$(uname -r)"
IS_WSL=false
grep -qi microsoft /proc/version 2>/dev/null && IS_WSL=true
IS_CODESPACES=false
[ -n "${CODESPACES:-}${CODESPACE_NAME:-}" ] && IS_CODESPACES=true

SUGGESTED_HOST=generic
case "$MODEL" in *UX8406*) SUGGESTED_HOST=zenbook-duo ;; esac

# ── helpers ──────────────────────────────────────────────────────────────────
have_whiptail() { command -v whiptail >/dev/null 2>&1 && [ -t 0 ] && [ -t 1 ]; }

cfg_get() { # <field> — read a value from user-config.nix; empty (success) if absent
  sed -nE "s/^[[:space:]]*$1[[:space:]]*=[[:space:]]*\"?([^\";]+)\"?;.*/\1/p" user-config.nix 2>/dev/null | head -n1 || true
}

module_seed() { # <module> <host> — saved choice > host seed > false
  local saved seed_file
  saved="$(cfg_get "$1")"
  if [ "$saved" = true ] || [ "$saved" = false ]; then
    echo "$saved"
    return
  fi
  seed_file="hosts/$2/setup-defaults.env"
  if [ -f "$seed_file" ]; then
    local var val
    var="MODULE_$(echo "$1" | tr '[:lower:]' '[:upper:]')"
    val="$(sed -nE "s/^$var=(true|false)$/\1/p" "$seed_file" | head -n1)"
    [ -n "$val" ] && { echo "$val"; return; }
  fi
  echo false
}

list_hosts() { # every hosts/<name>/ directory is a selectable profile
  local d
  for d in hosts/*/; do
    basename "$d"
  done
}

run_install() { # <host> — run install.sh as a CHILD (never exec: exec would
                # close the terminal window when install.sh exits), teed to a log
  local host="$1" log="$HOME/dome-install.log"
  echo "[dome] running ./install.sh --host $host  (logging to $log)"
  set +e
  ./install.sh --host "$host" 2>&1 | tee "$log"
  local rc=${PIPESTATUS[0]}
  set -e
  if [ "$rc" -ne 0 ]; then
    echo "[dome] install exited with status $rc — see $log (last lines below):" >&2
    tail -n 15 "$log" >&2
    return "$rc"
  fi
}

write_config() { # <host> <name> <email> then module vars m_python.. in env
  local host="$1" name="$2" email="$3"
  local username homedir
  username="${USER:-$(id -un)}"
  homedir="${HOME:-/home/$username}"
  if [ "$IS_CODESPACES" = true ]; then
    username=codespace
    homedir=/home/codespace
  fi
  cat > user-config.nix <<EOF
{
  # Generated by setup.sh on $(date +%F). Re-run ./setup.sh to change choices.
  name = "$name";
  email = "$email";

  # Module selections
  modules = {
    python = $m_python;
    node = $m_node;
    java = $m_java;
    ai = $m_ai;
    cloud = $m_cloud;
  };

  # Host profile - selects hosts/<name> for BOTH layers (Nix + system/)
  hostProfile = "$host";

  # Environment detection
  environment = {
    isCodespaces = $IS_CODESPACES;
    isWSL = $IS_WSL;
    username = "$username";
    homeDirectory = "$homedir";
  };

  # Additional user preferences
  gitDefaultBranch = "$(cfg_get gitDefaultBranch || true)";
  gitEditor = "$(cfg_get gitEditor || true)";

  # Development environment preferences
  preferredShell = "$(cfg_get preferredShell || true)";
  preferredEditor = "$(cfg_get preferredEditor || true)";
}
EOF
  # Backfill preference fields from the template when no previous config existed.
  sed -i 's/gitDefaultBranch = "";/gitDefaultBranch = "main";/' user-config.nix
  sed -i 's/gitEditor = "";/gitEditor = "vim";/' user-config.nix
  sed -i 's/preferredShell = "";/preferredShell = "zsh";/' user-config.nix
  sed -i 's/preferredEditor = "";/preferredEditor = "vim";/' user-config.nix
}

# ── non-interactive mode ─────────────────────────────────────────────────────
if [ "${1:-}" = "--defaults" ]; then
  HOST="${2:?usage: ./setup.sh --defaults <host>}"
  [ -d "hosts/$HOST" ] || { echo "unknown host profile: $HOST (have: $(list_hosts | tr '\n' ' '))" >&2; exit 1; }
  for m in "${MODULES[@]}"; do
    declare "m_$m=$(module_seed "$m" "$HOST")"
  done
  NAME="$(cfg_get name)"; EMAIL="$(cfg_get email)"
  NAME="${NAME:-$(git config --global user.name 2>/dev/null || true)}"
  EMAIL="${EMAIL:-$(git config --global user.email 2>/dev/null || true)}"
  write_config "$HOST" "${NAME:-Jowi Aoun}" "${EMAIL:-83415433+JowiAoun@users.noreply.github.com}"
  echo "[dome] wrote user-config.nix (host=$HOST, non-interactive)"
  exit 0
fi

# ── interactive mode ─────────────────────────────────────────────────────────
DETECT_TEXT="Detected machine:

  Distro:      $DISTRO
  Hardware:    $VENDOR $MODEL
  Kernel:      $KERNEL
  WSL:         $IS_WSL
  Codespaces:  $IS_CODESPACES

Suggested host profile: $SUGGESTED_HOST"

if have_whiptail; then
  whiptail --title "dome setup" --msgbox "$DETECT_TEXT" 16 70

  # host profile radiolist, suggestion pre-selected
  HOST_ITEMS=()
  while IFS= read -r h; do
    state=OFF
    [ "$h" = "$SUGGESTED_HOST" ] && state=ON
    HOST_ITEMS+=("$h" "hosts/$h" "$state")
  done < <(list_hosts)
  HOST="$(whiptail --title "dome setup" --radiolist \
    "Host profile for this machine:" 14 60 "${#HOST_ITEMS[@]}" \
    "${HOST_ITEMS[@]}" 3>&1 1>&2 2>&3)" || { echo "aborted"; exit 1; }

  # module checklist, seeded per precedence
  MOD_ITEMS=()
  for m in "${MODULES[@]}"; do
    state=OFF
    [ "$(module_seed "$m" "$HOST")" = true ] && state=ON
    MOD_ITEMS+=("$m" "" "$state")
  done
  CHOSEN="$(whiptail --title "dome setup" --checklist \
    "Modules to enable (space toggles, enter confirms):" 15 60 "${#MODULES[@]}" \
    "${MOD_ITEMS[@]}" 3>&1 1>&2 2>&3)" || { echo "aborted"; exit 1; }
  for m in "${MODULES[@]}"; do
    declare "m_$m=false"
  done
  for m in $CHOSEN; do
    m="${m%\"}"; m="${m#\"}"
    declare "m_$m=true"
  done

  NAME_DEFAULT="$(cfg_get name)"; NAME_DEFAULT="${NAME_DEFAULT:-$(git config --global user.name 2>/dev/null || echo 'Jowi Aoun')}"
  EMAIL_DEFAULT="$(cfg_get email)"; EMAIL_DEFAULT="${EMAIL_DEFAULT:-$(git config --global user.email 2>/dev/null || echo '83415433+JowiAoun@users.noreply.github.com')}"
  NAME="$(whiptail --title "dome setup" --inputbox "Your name (git commits):" 10 60 "$NAME_DEFAULT" 3>&1 1>&2 2>&3)" || exit 1
  EMAIL="$(whiptail --title "dome setup" --inputbox "Your email (git commits):" 10 60 "$EMAIL_DEFAULT" 3>&1 1>&2 2>&3)" || exit 1

  SUMMARY="host:    $HOST
name:    $NAME
email:   $EMAIL
modules:"
  for m in "${MODULES[@]}"; do
    v="m_$m"
    SUMMARY="$SUMMARY
  $m = ${!v}"
  done
  whiptail --title "dome setup — confirm" --yesno "$SUMMARY

Write user-config.nix?" 18 60 || { echo "aborted, nothing written"; exit 1; }

  write_config "$HOST" "$NAME" "$EMAIL"

  RUN_NOW=no
  whiptail --title "dome setup" --yesno \
    "Run the full install now?\n\nsystem layer (sudo) -> Nix -> home-manager.\nOutput is logged to ~/dome-install.log" 12 64 && RUN_NOW=yes
  # whiptail has torn down here — back on the normal terminal, so sudo/Nix
  # prompts below are visible and the shell survives (no exec).
  echo "[dome] wrote user-config.nix (host=$HOST)"
  if [ "$RUN_NOW" = yes ]; then
    run_install "$HOST"
  else
    echo "[dome] done. Run ./install.sh --host $HOST when ready."
  fi
else
  # plain-prompt fallback (no whiptail or no TTY-attached UI possible)
  echo "== dome setup =="
  echo "$DETECT_TEXT"
  echo
  printf 'Host profile [%s] (options: %s): ' "$SUGGESTED_HOST" "$(list_hosts | tr '\n' ' ')"
  read -r HOST
  HOST="${HOST:-$SUGGESTED_HOST}"
  [ -d "hosts/$HOST" ] || { echo "unknown host profile: $HOST" >&2; exit 1; }
  for m in "${MODULES[@]}"; do
    seed="$(module_seed "$m" "$HOST")"
    printf 'Enable module %-7s [%s] (y/n): ' "$m" "$seed"
    read -r ans
    case "${ans:-}" in
      y|Y) declare "m_$m=true" ;;
      n|N) declare "m_$m=false" ;;
      *) declare "m_$m=$seed" ;;
    esac
  done
  NAME_DEFAULT="$(cfg_get name)"; NAME_DEFAULT="${NAME_DEFAULT:-$(git config --global user.name 2>/dev/null || echo 'Jowi Aoun')}"
  EMAIL_DEFAULT="$(cfg_get email)"; EMAIL_DEFAULT="${EMAIL_DEFAULT:-$(git config --global user.email 2>/dev/null || echo '83415433+JowiAoun@users.noreply.github.com')}"
  printf 'Name [%s]: ' "$NAME_DEFAULT"; read -r NAME; NAME="${NAME:-$NAME_DEFAULT}"
  printf 'Email [%s]: ' "$EMAIL_DEFAULT"; read -r EMAIL; EMAIL="${EMAIL:-$EMAIL_DEFAULT}"
  write_config "$HOST" "$NAME" "$EMAIL"
  echo "[dome] wrote user-config.nix (host=$HOST)"
  printf 'Run the full install now (./install.sh --host %s)? (y/N): ' "$HOST"
  read -r go
  case "${go:-}" in
    y|Y) run_install "$HOST" ;;
    *) echo "[dome] done. Run ./install.sh --host $HOST when ready." ;;
  esac
fi
